### ISSUE TITLE
HA 0.73无法通过微信小程序登陆

### ISSUE THREAD

**Issue by plutosherry** [haoctopus/molohub#1]
HA 0.73无法通过微信小程序登陆，输入用户名+密码后点击登陆无反应

**Comment by haoctopus** [comment]
@plutosherry 收到，在论坛里也看到了哈，我们在紧急修复中，感谢反馈！

**Comment by yulongying** [comment]
bug已经修复，原因是HA使用了fetch方法没有带credentials 字段，导致旧版本的浏览器在发送请求的时候没有带登录session的cookie。
修复方法：
1、molohub对此bug进行暂时的兼容
2、官方调用fetch方式带上credentials 字段，已经合入主线 https://github.com/home-assistant/home-assistant-js-websocket/pull/54

**Comment by haoctopus** [comment]
bug已经修复，原因是HA使用了fetch方法没有带credentials 字段，导致旧版本的浏览器在发送请求的时候没有带登录session的cookie。
修复方法：
1、molohub对此bug进行暂时的兼容
2、官方调用fetch方式带上credentials 字段，已经合入主线 home-assistant/home-assistant-js-websocket#54
